### ISSUE TITLE
Cut release? 

### ISSUE THREAD

**Issue by lorengordon** [arabold/aws-to-slack#50]
Time to cut a release? There are 116 commits since the last release, including several new parsers and the async refactor. Feels like maybe it's time, that waiting will just make it harder as the changes build up... 😁 Thanks!

**Comment by ghernandez16** [comment]
Hi, 
Trying to use this tool. I used cloudformation and then updated the parsers, index.json and slack.json and added the test and target to the lambda function. Are there any changes in node modules??
I'm testing with GuardDuty but the parser is using the generic one.
What could be the reason?
Thanks

**Comment by homeyjd** [comment]
Hey @ghernandez16.  Not sure what you're talking about with `index.json` -- do you mean you updated the environment variables of the Lambda function?

Unfortunately, we don't have access to the S3 buckets referenced in the CloudFormation template.  So to use the new version of the code, you deploy the CloudFormation template _then build locally and replace the function's code_.

The command to deploy-and-push looks something like this:
```
AWS_REGION=us-west-2 LAMBDA_NAME=myLambdaFunction make deploy
```

If you're managing multiple deployments, I recommend checking out this section of the readme.  It will automate these steps for you:
https://github.com/arabold/aws-to-slack#managing-multiple-deployments

**Comment by homeyjd** [comment]
@lorengordon I totally agree!  I was really hoping arabold would show up to offer to push the changes to S3 in coordination with a release-tag, but c'est la vie.

**Comment by lorengordon** [comment]
I'd suggest working on a CI setup that can handle the deploy, on tags. 😁

**Comment by ghernandez16** [comment]
Hi @homeyjd,
I use the cloudformation and then updated the function's code that were different (index,js, slack.js and the parsers). Don't know if this is the right way to do it.
Don't know where to run the command yo mention. This is what I currently have. i also changed it to Node 8.10.
Thanks for the help.
<img width="104" alt="Screenshot_4" src="https://user-images.githubusercontent.com/49002162/56918625-1d38cd80-6a84-11e9-94cf-a96fecc6482b.png">

**Comment by homeyjd** [comment]
Pushed a release manually for now: https://github.com/arabold/aws-to-slack/releases/tag/1.2.0

Good callout for a CI.  Just set up my fork to use CircleCI: https://circleci.com/gh/homeyjd/aws-to-slack/tree/master
but [my fork has diverged a lot](https://github.com/arabold/aws-to-slack/compare/master...homeyjd:master)...

@lorengordon You've been pretty active on this project -- really appreciate your feedback.  What would you think of merging more changes?  There's value in being able to identify type/source of AWS events, so I separated "matching an event" from "processing an event" on my fork.  Locally, I've been able to re-use the event-matching portion for event-type filters, and I added an [SES integration](https://github.com/homeyjd/aws-to-slack/blob/master/src/ses.js) instead of those silly-simple SNS emails.

Example of how parser has changed: [a current simple parser](https://github.com/arabold/aws-to-slack/blob/1c7ca3510d3cef35a8656f424044aab396c29840/src/parsers/autoscaling.js) vs [a functional concerns-based approach](https://github.com/homeyjd/aws-to-slack/blob/ee091ae1e0d635a71c447dc9feccd00812386e8a/src/parsers/autoscaling.js).

**Comment by homeyjd** [comment]
@ghernandez16 That kinda looks like the AWS Console web interface.  Updating the Lambda function's code within the Console interface won't work.  
I'm suggesting you pull down the repository to your local machine and run that command inside the repo's folder.

**Comment by ghernandez16** [comment]
Hi,
I'm not a developer, neither CI or github knowledge. I was just trying to make use of this project for my accounts. 
Could you show me how to build this so I can upload the release.zip to Lambda? Not sure how to do it.
Thanks,

**Comment by lorengordon** [comment]
> What would you think of merging more changes? There's value in being able to identify type/source of AWS events, so I separated "matching an event" from "processing an event" on my fork

The new method looks simpler and more streamlined. I'm a fan of separating concerns and making it easier to write parsers for more services. :)

> I added an SES integration instead of those silly-simple SNS emails.

I don't really have an opinion on this one... I'm here for the slack integration, trying to stop setting up email notifications. :) I agree though that the SNS emails are not useful for humans, and so anything to pretty them up a bit would be appreciated by those who have that email requirement...

**Comment by ghernandez16** [comment]
Ok, Found how to do it... Think the issue is just with GuardDuty for me. CW Alarms working fine with graph and RDS notifications fine as well, but guardduty notifications are falling under generic.
I configure guardduty with cwevents for this. Thinking on doing the same with health dashboard. 
Is this how is supposed to be configured? If it is I'm having that issue. 
Thanks,

**Comment by ghernandez16** [comment]
For RDS it is also using generic parser.

**Comment by homeyjd** [comment]
New release tag was cut!  Also merged additional branches to support other additions. 
Closing comment thread...
