### ISSUE TITLE
Support different slack channels per aws service

### ISSUE THREAD

**Issue by fernandoaguilar** [arabold/aws-to-slack#60]
Hi I love what you have built here and recently set up a codebuild notification pipeline with ease. I was hoping there was a way to support sending messages to different slack hook urls on a per service basis, i.e. send codedeploy messages to a different channel. I could work on writing the code myself or if theres a way to do this already then please advise.

**Comment by homeyjd** [comment]
I considered something similar but opted against.  

Since AWS doesn't charge for defining multiple Lambda functions, it makes a little more sense to deploy the stack multiple times with different channel endpoints.  Personally, I created "notice" / "warning" / "alert" stacks that deliver to different channels, then configured CloudWatch/etc.al. to deliver alerts to the appropriate channel based on the severity of the alarm or message.  This kept the code clean, and makes reviewing alerting configurations in AWS super-easy!

The downside is re-deploying Lambda multiple times after an update to the repo.  I documented a simple multi-deploy pattern [in the readme](https://github.com/arabold/aws-to-slack#managing-multiple-deployments), if that helps!

**Comment by fernandoaguilar** [comment]
Very helpful thanks, I went ahead and just set up another lambda. It was quick and easy. Thanks for responding. I might also look at doing something similar to your cloudwatch alerts going to different channels depending on severity.
